# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.define :neo01 do |neo|
    neo.vm.network :hostonly, "192.168.33.33"
    #neo.vm.base_mac = "60672018648d"
    neo.vm.share_folder "website", "/var/www", "./www", owner: "vagrant", group: "www-data"
    neo.vm.host_name = "www.example.me"
  end

  config.vm.provision :chef_solo do |chef|
    chef.roles_path = "roles"
    chef.cookbooks_path = ["site-cookbooks", "cookbooks"]
    chef.add_role "vagrant-example"
  end
end

